import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "10Q - Quiz App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
					rel="stylesheet"
				/>
			</head>
			<body className={`${inter.className} bg-neutral-900`}>
				<Providers>
					<div className="flex flex-col min-h-screen sm:w-3/4 md:w-1/2 mx-auto sm:border border-black">
						<Header />
						<main className="px-3 flex-grow bg-gray-950 text-neutral-200">
							{children}
						</main>
						<hr className="border-gray-900 border-t-2" />
						<Footer />
					</div>
				</Providers>
			</body>
		</html>
	);
}
